name: demirli_tech_website

description: Demirli Tech flutter web site project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  web:
    generate: true
    image_path: "assets/images/logo/demirli_tech_only_logo_web_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/badges/
    - assets/images/contact/
    - assets/images/logo/
    - assets/images/product/
    - assets/images/product/kost/
    - assets/images/product/oto_plan/
    - assets/images/product/qr_projem/
    - assets/images/product/reb_ar/
    - assets/images/service/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Light.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic

